Refactor: replace moment.js with day.js
JordanKnott/taskcafe pull request #77
Opened 2020-10-01 20:15 UTC by nurseiit

* **Please check if the PR fulfills these requirements**
- [x] You have read the contribution guidelines [guidelines](https://github.com/JordanKnott/taskcafe/blob/master/CONTRIBUTING.md)
- [x] The commit message follows our [guidelines](https://github.com/JordanKnott/taskcafe/blob/master/CONTRIBUTING.md#git-commit-message-style)
- [ ] Docs have been added / updated (for bug fixes / features)

* **What kind of change does this PR introduce?** (Bug fix, feature, docs update, ...)
Refactor all legacy `moment.js` with modern `day.js`. 

* **What is the current behavior?** (You can also link to an open issue here)
Moment.js is used in frontend client for pretty much anything date related.
Fixes #74 

* **What is the new behavior (if this is a feature change)?**
N/A

* **Does this PR introduce a breaking change?** (What changes might users need to make in their application due to this PR?)
No.

* **Other information**:

2020-10-04 13:25 UTC, tauqeernasir approved these changes

2020-10-10 21:24 UTC, JordanKnott commented
Can you squash the commits?

2020-10-10 21:28 UTC, JordanKnott requested changes
Except for squashing commits & moving some of the `extends` into `src/App/index`, everything looks good!

2020-10-10 21:28 UTC, JordanKnott commented on frontend/src/shared/components/Lists/index.tsx
> +dayjs.extend(isSameOrAfter);
We should probably move this to `src/App/index.tsx`

2020-10-10 21:28 UTC, JordanKnott commented on frontend/src/shared/components/DueDateManager/index.tsx
> +dayjs.extend(customParseFormat);
We should probably move this to `src/App/index.tsx`

2020-10-10 21:28 UTC, JordanKnott commented on frontend/src/shared/components/Lists/metaFilter.ts
> +dayjs.extend(isBetween);
We should probably move this to `src/App/index.tsx`

2020-10-20 21:06 UTC, merged

2020-10-20 21:07 UTC, JordanKnott commented
Since this PR has been stale for a while, I rebased off of master & squashed the commits. I also moved the plugins to `src/index.tsx`. This PR has now bee merged.